# Telemetry Configuration

backends:
  - prometheus
  - stdout

prometheus:
  pushgateway: http://prometheus-pushgateway:9091
  job_name: hypersync
  push_interval: 30

grafana:
  loki_endpoint: http://loki:3100
  datasource: hypersync

datadog:
  api_key: ${DATADOG_API_KEY}
  site: datadoghq.com

cloudwatch:
  region: us-west-2
  namespace: HyperSync

metrics:
  enabled: true
  retention_days: 30
  aggregation_interval: 60

events:
  enabled: true
  retention_days: 90
  buffer_size: 1000

receipts:
  enabled: true
  storage: s3
  bucket: hypersync-receipts
  retention_days: 365
